### ISSUE TITLE
CLLI  List

### ISSUE THREAD

**Issue by WesWrench** [tumi8/hloc#7]
Hello,

I haven't been able to read all the source code for your project yet, I'm still on your pdf (tma2017_paper8.pdf).

While reading your readme I saw that you mentioned "Unfortunately we could not find a public available CLLI list.".

Looking at wikipedia (https://en.wikipedia.org/wiki/CLLI_code)

I grab some examples and typing on google:
"MALTON22CG1 DLLSTXRNDS1 OTWAON080MD SWASONXTSG1 filetype: txt"

Google return: http://wedophones.com/Manuals/TelcoData/clli-lat-lon.txt

Is this what you are looking for?
There are also other different formats here: http://wedophones.com/Manuals/TelcoData/

Best regards,

**Comment by sattler** [comment]
Hi,

we could not find any sources at that time but these look promising. We only use the location part of the clli code so you would need to remove the network identifying part after the first 6 characters. I will add a hint to this page in the readme

Best regards,
Patrick

**Comment by WesWrench** [comment]
Hello,

The first six characters are the city (four letters) and province / state (two letters).
The other characters give the identifier of the equipment (eg Switch).
Since there are several equipment per city, which latitude / longitude to choose for a city?
Why not use the full code to gain precision?

Best regards,

**Comment by sattler** [comment]
Yes due to that structure we decided to only use the first six characters. HLOC cannot confirm a location with more precision as the RTT measurements are not that granular. Also to our experience the first six letters are more present in router domains compared to the full identifier. If you want you can change the code in your own fork in order for it to use the full clli code but we will currently not change that as the support here is currently only in maintenance without any new features.

It's a good question which lat/lon you should use. If you use our location collection and merger it wont matter much as the clli lat lon is the last one it would use as a cities location.

I hope this helps!

Best regards,
Patrick
